[project]
name = "dataworks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arrrrrmin", email = "43553423+arrrrrmin@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dask>=2026.7.1",
    "duckdb>=1.5.0",
    "netcdf4>=1.7.4",
    "requests>=2.32.5",
    "xarray>=2026.7.0",
]

[project.scripts]
dataworks = "dataworks:main"

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
